Release 8.315 of Pythia.

diff --git a/examples/runmains b/examples/runmains
--- a/examples/runmains
+++ b/examples/runmains
@@ -32,7 +32,6 @@ Configuration options.
 --pre=PRE   : Insert a command before running each main, e.g. a debugger call.
 BLOCKTEXT
 OPTIONS="-h --h -help --threads --skip --run --pre"
-LOGFILE="runmains.log"
 main132="-c main132.cmnd -o main132.hepmc"
 main133="-c main133.cmnd -o main133.hepmc"
 main134="-c main134.cmnd -o main134.hepmc"
@@ -59,24 +58,27 @@ function warn() {
 # FUNCTION: Compile and run a set of examples using a common lockfile.
 ################################################################################
 function runmains() {
-    while [ -f "$LOGFILE" ]; do
-	read -a MAINS < $LOGFILE
-	if (("${#MAINS[@]}" > 1)); then echo "${MAINS[@]:1}" > $LOGFILE
-	else rm -f $LOGFILE; fi
-	MAIN=${MAINS[0]}
+    for MAIN in "${MAINS[@]}"; do
 	MAIN=${MAIN%.cc}
-	USE=true
-	for N in $SKIP; do
-	    if [ "$MAIN" = "main$N" ]; then USE=false; break; fi;
-	done
-	if [ ! -z "$RUN" ]; then USE=false; fi
-	for N in $RUN; do
-	    if [ "$MAIN" = "main$N" ]; then USE=true; break; fi;
-	done
-	if [ "$USE" = false ]; then continue; fi
-	eval ARGS=\$${MAIN}
-	make $MAIN
-	{ time $PRE ./$MAIN $ARGS ; } > $MAIN.log 2>&1
+	if { set -C; 2>/dev/null > "$MAIN.log"; }; then
+    	    USE=true
+    	    for N in $SKIP; do
+    	        if [ "$MAIN" = "main$N" ]; then USE=false; break; fi;
+    	    done
+    	    if [ ! -z "$RUN" ]; then USE=false; fi
+    	    for N in $RUN; do
+    	        if [ "$MAIN" = "main$N" ]; then USE=true; break; fi;
+    	    done
+    	    if [ "$USE" = false ]; then continue; fi
+    	    eval ARGS=\$${MAIN}
+    	    set +e # Continue on error.
+	    set +C # Allow writing to the log file.
+    	    make $MAIN
+    	    { time $PRE ./$MAIN $ARGS ; } > $MAIN.log 2>&1
+    	    set -e # Stop on error.
+	else
+	    sleep 0.1
+	fi
     done
 }
 
@@ -107,11 +109,9 @@ done
 
 # Build the parallel runs.
 MAINS=(main[0-9][0-9][0-9].cc); THREAD=0
-echo "${MAINS[@]}" > $LOGFILE
 if [ -z $THREADS ]; then THREADS=1; fi
 while ((THREAD < THREADS)); do
     ((THREAD++))
     runmains &
-    sleep 1
 done
 wait
